### ISSUE TITLE
change label prop `data` -> `datum` where appropriate

### ISSUE THREAD

**Issue by boygirl** [FormidableLabs/victory-chart#116]

**Comment by cpb** [comment]
Should this include data components (like line segment, bar, point etc) as well as the label components?

**Comment by boygirl** [comment]
yes please!

**Comment by cpb** [comment]
- [ ] VictoryArea, AreaLabel
- [ ] VictoryArea, Area
- [ ] VictoryBar, BarLabel
- [ ] VictoryBar, BarLabel
- [ ] VictoryLine, LineLabel
- [ ] VictoryLine, LineSegment
- [ ] VictoryScatter, Point

Maybe:
- [ ] VictoryArea helper-methods
- [ ] VictoryBar, helper-methods
- [ ] VictoryChart, helper-methods
- [ ] VictoryScatter, helper-methods
- [ ] Helpers, data
- [ ] Helpers, domain
- [ ] Helpers, scale

**Comment by cpb** [comment]
Questions:
- [ ] Should we be passing `props` into helper functions? 
  - Refactoring VictoryScatter Point's prop `data` to `datum` breaks https://github.com/FormidableLabs/victory-chart/blob/refactors-data-to-datum/src/components/victory-scatter/helper-methods.js#L41-L54
- [ ] Should we change the call to `getPath` to maintain the `props` signature? https://github.com/FormidableLabs/victory-chart/commit/92f5689b61234cb0352ff6ee185b24772f5ab84b
- [ ] Or, should we change the signature of `getPath`? Here, we sort of get both. The dependencies are explicit in the signature: https://github.com/FormidableLabs/victory-chart/commit/63ced9b712e0c069db1704289541767d02b22cc4
- [ ] For helpers that act on datum, rather than data (a list of datum), should we refactor their arguments to show that? IE: don't juggle the `datum` value from the Point props into the `data` field for the getPath helper above? There are some helpers in FormidableLabs/victory-core that could be changed in this way too.

**Comment by cpb** [comment]
@boygirl there has been a flurry of activity on this, let me bring you up to speed.

I started in victory-chart, changing `data` to `datum.` That carried me into victory-core to change VictoryLabel to use `datum` instead of `data.` VictoryPie also consumes VictoryLabel, so I updated `data` to `datum` there too.

This is the top of the tree of merges & issue closing: https://github.com/FormidableLabs/victory-core/pull/27

Pleased to learn if I missed something!
