### ISSUE TITLE
Add an errorBar component for out of the box use

### ISSUE THREAD

**Issue by stefvhuynh** [FormidableLabs/victory-chart#195]
It would be useful to have an `errorBar` component that shows degrees of error (confidence intervals) around points on a plot, the tops of bars on bar charts, etc. 

For example: https://github.com/FormidableLabs/victory-examples/issues/11

**Comment by ebrillhart** [comment]
@boygirl I forget exactly what we talked about re: whether this is going to be something that can be plugged into dataComponent or whether there will be a new errorComponent prop? From what I'm picturing the errorComponent way would be more flexible (since it would just essentially be an overlay over the existing data component instead of needing to be customized for individual chart styles) but I might be missing something.

**Comment by boygirl** [comment]
It's going to need it's own specialized data format, so I think it might make more sense as its own component. Can you do a bit of research and present a few potential formats for expressing errors. We need to support errors in x and y, and asymmetric errors.

**Comment by ebrillhart** [comment]
@boygirl 
It seems like error bars like we've already conceptualized them are far and away the most popular and commonly used, on bar, scatter, line, area, etc. (Tufte is unopinionated on this, but the one clear example of error display I found showed a similar bar component.) Some line charts use error lines above and below the main data line, but I figure consistency is preferred right now. Our component could be capable of having both x and y error bars, and use some logic to determine which ones actually need to show up. For bar charts, the error component attaches to the top/y-value of the bar, centered on the x-value, and for all other charts it centers on the datapoint.

As far as I can tell, these will be the bigger challenges: 
1) handling inconsistent data descriptions/values - some data may just be "error: 5", which would tend to default to y, but what if on some datasets it's an x error? just assume it's y unless error: {x: 5} is used? we'll need to be able to parse integers, objects, and objects with arrays to find error values.

2) determining what the positive/negative values are for a datum with asymmetric error values - maybe we force people to use a coordinate format similar to domain? like error: {x: [5, 8], y: [6, 9]} with a [positive, negative] assumption? again, this might be tricky to handle when someone imports a dataset, because I've seen really inconsistent ways in how this is expressed within data, eg error, margin of error, +/-, etc. maybe at some point we allow the user to specify what error values are being called within their dataset somehow? If people are just entering their data by hand, it's easy to let them know the preferred format.

3) Figuring out the best way to pass down props to the error component, since it seems like in some ways it should be part of renderData for each chart component, but that also seems cluttered and difficult to return properly (this is probably less of a big deal, but something I noticed when looking at the existing code handling of passing data props down to child components).
