### ISSUE TITLE
Victory.js victory-chart & lodash-webpack-plugin Incompatibility

### ISSUE THREAD

**Issue by joshburgess** [FormidableLabs/victory-chart#289]
I'm not sure where this should go, so I'm just going to post it in both repos & link them, but I'm having an issue where using lodash-webpack-plugin for my production build is breaking some internal code in the victory.js victory-chart library. 

Specifically, it's in the scale.js helper utility and is failing on line 71:

var axisData = allData.map(accessor);

The error in the chrome console is:

scale.js:71 Uncaught TypeError: r.map is not a function

And this was while using a horizontal stack chart made up of VictoryStack & VictoryBar components.

To be clear, if I comment out usage of the lodash webpack plugin and rebuild, all works as it should. I'm not sure what exactly the issue is, but let me know if I can provide any extra detail you might need. 

lodash/lodash-webpack-plugin#38

**Comment by ryan-roemer** [comment]
@joshburgess -- Do you have an online repro we can try ourselves? Also, what are your configs for the lodash webpack plugin? (E.g., which of the optimizations have you disabled? Generally you always need _some_ optimizations disabled...)

**Comment by joshburgess** [comment]
Unfortunately, I do not as it's a large single page app project for my day job. I'm actually not passing any special configuration to the lodash webpack plugin. It's just using the default settings.

By "optimizations disabled" do you mean that I need to add some extra opt-in features to cover what victory is using internally? I guess I was just under the impression that this would only affect my userland code using lodash and not npm modules I was using, thinking that they were already reduced to the bare minimum of lodash functions needed for their own use cases.

**Comment by ryan-roemer** [comment]
@joshburgess -- I mean which of https://github.com/lodash/lodash-webpack-plugin#feature-sets have you disabled? You usually need at least _some_ for any large app because otherwise too much of lodash internals are stripped away. Can you paste your actual lodash webpack configuration plugin?

For example, here's the configuration we use in victory: https://github.com/FormidableLabs/builder-victory-component/blob/master/config/webpack/webpack.config.js#L66-L71

```js
    new LodashModuleReplacementPlugin({
      "currying": true,
      "paths": true,
      "placeholders": true,
      "shorthands": true
    }),
```

You can see some previous issues we had _without_ these disables at: 

* https://github.com/FormidableLabs/builder-victory-component/pull/64
* https://github.com/FormidableLabs/victory-chart/issues/241

**Comment by joshburgess** [comment]
Yeah, nevermind about this, I guess. 

I went through all of the options and "flattening: true" was the one that was required. 

I guess I just wasn't fully aware of how lodash-webpack-plugin works. Didn't realize it has to be tweaked based on any npm modules that are pulled in and used. Sorry about that. Closing the issue now.
