### ISSUE TITLE
A bar is positioned outside an axis 

### ISSUE THREAD

**Issue by iokhotnikov** [FormidableLabs/victory-chart#301]
Hello, 
I've reproduced an issue with a bar. 
![victory-bar-bug](https://cloud.githubusercontent.com/assets/16080854/16950545/84f86c62-4dc9-11e6-8612-1c9aec0c819a.png)

Here is a code sample: https://jsfiddle.net/h5j7Lx4d/ 
Is it expected behavior for Victory Charts?

**Comment by boygirl** [comment]
@iokhotnikov if you don't set a domain, the automatic domain is set to include your data only without any padding. You can solve this by setting a domain manually for VcitoryChart, or by using the `domainPadding` prop on VictoryChart. So this is expected behavior, but I agree that it could be done better. 

@ebrillhart what do you think about calculating an automatic `domainPadding` for VictoryChart for grouped data?

**Comment by ebrillhart** [comment]
@boygirl that definitely seems like something I could work on!

**Comment by ebrillhart** [comment]
fixed with #313
